# -------------------------------------
# Based on
# -------------------------------------

FROM postgres:16.14

#-------------------------------------
# INFO
# -------------------------------------
LABEL author="Enrico Basciu"
LABEL author_email="enricobasciu@outlook.it"
LABEL author_nickname=""
LABEL project="CONDOMICIO BE - local"
LABEL version = "1.1.1"

# -------------------------------------
# Packages
# -------------------------------------

# -------------------------------------
# Add Postrgres INIT
# -------------------------------------

ADD ./ ./